---
title: 'Task 11: Controlling categorical variables (factors)'
author: "McKay Davis"
output: 
  html_document:
    code_folding: hide
    theme: united
    keep_md: TRUE
---

```{r setup, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = 'center', fig.width = 12, fig.height = 6)

setwd("/Users/mckaydavis/Documents/git/Math_335")

library(tidyverse)
library(forcats)
library(readr)
library(ggplot2)

stock <- readRDS("./Case_Study_04/Class_Task_08/tidyDowRds.Rds")

month_levels <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
```


```{r}
stock %>%
  filter(!is.na(year_end)) %>%
  mutate(month_endI = factor(month_end, levels = month_levels)) %>%
  ggplot(aes(y = value, x = month_endI, col = variable)) +
    geom_point() +
    facet_wrap( ~ year_end) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 75, vjust = 1, hjust = 1)) +
    labs(y = "returns", x = "year of return", title = "Index Return Accuracy of Darts vs Pros")
```

The plot shows variation between darts and pros and their accuracy in predicting the DJIA (based on my understanding of the data anyway). Variability is obvious in both dart and pro predictions. It is hard to say if one is more accurate than the other.

I would've liked to add a smooth line to the DJIA but couldn't figure out how. [Any ideas?](mailto::dav13037@byui.edu)
